#!/bin/bash
# script pour faire la bascule entre mode focus et mode navigation, en lui affectant une seule touche du clavier
# nécessite le paquet : xdotool
# licence GPL v3
# auteur : association Aciah - avril 2024

sleep 0.5 && xdotool key Insert+a
exit 0



# Lorsque le lecteur d'écran est actif, et que l'on arrive dans une zone de saisie, 
# on ne peut écrire dans cette zone que si on entend : mode focus.  
# On peut basculer entre mode focus et mode navigation avec le raccourci : Insert + a.  
# Mais nous proposons de le faire avec une seule touche, celle qui s'appelle 'Page Bas' ou 'Page Down' , si on ne s'en sert pas souvent. 
# Pour cela nous avons créé le script ci-dessus nommé : bascule-focus-nav.sh que nous avons enregistré dans /usr/local/bin



Créer ce raccourci : la méthode ci-dessous correspond à la distribution Linux-Mint xfce, donc aussi à Aciah-Linux.

1 – Ouvrir le menu Whisker en faisant : {{MAJ + WIN + F1}} ou {{Win + L}}
2 – Saisir le mot : {{clavier}},  et valider avec {{Entrée}}. On arrive à une nouvelle fenêtre.
3 – {{Flèche-Droite}} une fois pour arriver à : {{raccourcis d’applications.}}
4 –{{TAB}}uler jusqu’au bouton : ajouter . Ou bien faire : {{ALT + J}}.
5 – On arrive à une zone de saisie et on entend : entrez la commande.
	Entrer alors cette commande : sh /usr/local/bin/bascule-focus-nav.sh
	et valider avec : {{ALT + V}}
6 – Ensuite on n’entend rien mais il faut quand même appuyer sur les touches du clavier qu'on veut utiliser.
7 – Appuyer ici sur la touche 'Page bas'. La manipulation est enregistrée.
8 – Fermer avec {{ALT + F4}}.

Mais, il faut le redire, attention à ne pas entrer en conflit avec un raccourci déjà existant !

